### ISSUE TITLE
parameter 'value' expects a value of type Undef, String, or Boolean, got Integer

### ISSUE THREAD

**Issue by daveseff** [lcrownover/facter#2]
Is there any reason why we can not set integer value facts?

**Comment by lcrownover** [comment]
Hey Dave,

I've updated the parameter to accept integers. Puppet documentation has no mention of handling them, but since this module uses yaml to store external facts, it should work just fine. Thanks for bringing it to my attention!

[267cb5d](https://github.com/lcrownover/facter/commit/267cb5d72b84923eddb9bd95b2c3d7d27e6282b5)
